# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Xuanzhao
last_name: Li
contact_note: >
  xzli@genetics.ac.cn
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  I am currently a Ph.D. student at the Institute of Genetics and Developmental Biology, Chinese Academy of Sciences, since Fall 2023. My research focuses on wheat genomics and the patterns of gene expression changes during distant hybridization. Prior to starting my Ph.D., I participated in several large-scale genomics projects as both a lead contributor and team member, including the rice pan-genome project and the locust genome project. I expect to graduate in 2027 and am currently seeking suitable career opportunities.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: Bioinformatics, Genomics # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://xuanzhaoli.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button

remote_theme: alshedivat/al-folio

# Jekyll core only
markdown: kramdown
highlighter: rouge

include: ["_pages"]

exclude:
  - README.md
  - vendor
# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# External service URLs for repository page
# To use a different instance or service for displaying GitHub stats and trophies,
# update these URLs. These are used in the repository templates.
external_services:
  github_readme_stats_url: https://github-readme-stats.vercel.app
  github_profile_trophy_url: https://github-profile-trophy.vercel.app
